### ISSUE TITLE
ts2python AssertionError

### ISSUE THREAD

**Issue by satels** [jecki/ts2python#13]
```python
Could not check whether grammar requires recompiling, because grammar was not found at: ts2python.ebnf
Traceback (most recent call last):
  File "/usr/local/bin/ts2python", line 8, in <module>
    sys.exit(main())
  File "ts2pythonParser.py", line 1384, in main
    error_file = process_file(file_names[0], file_names[0][:-3] + '.py')
  File "ts2pythonParser.py", line 1143, in process_file
    result, errors = compile_src(source)
  File "ts2pythonParser.py", line 1103, in compile_src
    results = full_pipeline(source, preprocessing.factory, parsing.factory,
  File "DHParser/pipeline.py", line 235, in full_pipeline
    return run_pipeline(junctions, {cst.stage: cst}, target_stages)
  File "DHParser/pipeline.py", line 209, in run_pipeline
    results[t] = process_tree(junction[1](), tree)
  File "DHParser/compile.py", line 557, in process_tree
    result = tp(tree)
  File "DHParser/compile.py", line 252, in __call__
    result = self.compile(self.tree)
  File "ts2pythonParser.py", line 437, in compile
    result = super().compile(node)
  File "DHParser/compile.py", line 338, in compile
    result = compiler(node)     
  File "ts2pythonParser.py", line 495, in on_document
    return '\n\n'.join(self.compile(child) for child in node.children
  File "ts2pythonParser.py", line 495, in <genexpr>
    return '\n\n'.join(self.compile(child) for child in node.children
  File "ts2pythonParser.py", line 437, in compile
    result = super().compile(node)
  File "DHParser/compile.py", line 338, in compile
    result = compiler(node)     
  File "ts2pythonParser.py", line 616, in on_type_alias
    types = self.compile(node['types'])
  File "ts2pythonParser.py", line 437, in compile
    result = super().compile(node)
  File "DHParser/compile.py", line 338, in compile
    result = compiler(node)     
  File "ts2pythonParser.py", line 790, in on_types
    assert all(nd[0].name == 'literal' for nd in node.children)
AssertionError
```

ts file:

```typescript
import {ChartArea} from './geometric.js';

export type LayoutPosition = 'left' | 'top' | 'right' | 'bottom' | 'center' | 'chartArea' | {[scaleId: string]: number};

export interface LayoutItem {
  /**
   * The position of the item in the chart layout. Possible values are
   */
  position: LayoutPosition;
  /**
   * The weight used to sort the item. Higher weights are further away from the chart area
   */
  weight: number;
  /**
   * if true, and the item is horizontal, then push vertical boxes down
   */
  fullSize: boolean;
  /**
   * Width of item. Must be valid after update()
   */
  width: number;
  /**
   * Height of item. Must be valid after update()
   */
  height: number;
  /**
   * Left edge of the item. Set by layout system and cannot be used in update
   */
  left: number;
  /**
   * Top edge of the item. Set by layout system and cannot be used in update
   */
  top: number;
  /**
   * Right edge of the item. Set by layout system and cannot be used in update
   */
  right: number;
  /**
   * Bottom edge of the item. Set by layout system and cannot be used in update
   */
  bottom: number;

  /**
   * Called before the layout process starts
   */
  beforeLayout?(): void;
  /**
   * Draws the element
   */
  draw(chartArea: ChartArea): void;
  /**
   * Returns an object with padding on the edges
   */
  getPadding?(): ChartArea;
  /**
   * returns true if the layout item is horizontal (ie. top or bottom)
   */
  isHorizontal(): boolean;
  /**
   * Takes two parameters: width and height.
   * @param width
   * @param height
   */
  update(width: number, height: number, margins?: ChartArea): void;
}

```

**Comment by jecki** [comment]
Thanks for the bug report. The latest commit in the git repository has fixed this. The fix will be included in the upcoming Version 0.7.1 in PYPI.

Here is the result for your source-code. (Imports are ignored by ts2python):

```
    LayoutPosition = Union[Literal['left', 'top', 'right', 'bottom', 'center', 'chartArea'], Dict[str, float]]
    
    
    class LayoutItem:
        position: LayoutPosition
        weight: float
        fullSize: bool
        width: float
        height: float
        left: float
        top: float
        right: float
        bottom: float
    
        def beforeLayout(self) -> None:
            pass
    
        def draw(self, chartArea: 'ChartArea') -> None:
            pass
    
        def getPadding(self) -> 'ChartArea':
            pass
    
        def isHorizontal(self) -> bool:
            pass
    
        def update(self, width: float, height: float, margins: Optional['ChartArea'] = None) -> None:
            pass
```

Have a nice day!
